platform :ios, '9.0'

target 'test2' do
  # Add React Native pods
  ...

  # Add React Native Safe Area Context pod
  pod 'react-native-safe-area-context', path: '../node_modules/react-native-safe-area-context'
end

